version: '3.8'
services:
   mysqldb:
      image: mysql
      container_name: mysqldb
      environment:
         MYSQL_DATABASE: test_db
         MYSQL_ROOT_PASSWORD: root
      networks:
      - springboot-mysql-net
   springboot-resftul-webservices:
      container_name: springboot-resftul-webservices
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
      - 8080:8080
      depends_on:
      - mysqldb
      networks:
      - springboot-mysql-net
      restart: on-failure

networks:
   springboot-mysql-net:
